export {
  UuidSchema,
  IsoDateTimeSchema,
  WorkspaceRoleSchema,
  ProviderTypeSchema,
  ConnectionStatusSchema,
  ConnectivityModeSchema,
  AuthStatusSchema,
  AccountStatusSchema,
  UserStatusSchema,
  UserSchema,
  AuthUserSchema,
  EmailSchema,
  PasswordSchema,
  LoginRequestSchema,
  SignupRequestSchema,
  MfaMethodKindSchema,
  MfaChallengeRequestSchema,
  PasswordChangeRequestSchema,
  ForgotPasswordRequestSchema,
  ResetPasswordRequestSchema,
  VerifyEmailRequestSchema,
  DesktopAuthStartRequestSchema,
  DesktopAuthPollRequestSchema,
  DeviceRecordSchema,
  SessionRecordSchema,
  SecurityActivityItemSchema,
  MfaStatusSchema,
  ConnectionMethodSchema,
  ProviderConnectionSummarySchema,
  PlanTierSchema,
  SubscriptionStatusSchema,
  PlanSummarySchema,
  BillingSandboxActionSchema,
  BillingSummarySchema,
  WorkspaceSchema,
  ProjectSchema,
  AssetSchema,
  GenerationJobSchema,
  ProviderConnectionSchema,
  ApiErrorDetailSchema,
  ApiErrorSchema,
  DiagnosticCheckSchema,
  DiagnosticsSchema,
  HealthResponseSchema,
  ReadyResponseSchema,
  scorePasswordStrength,
  type UserInput,
  type AuthUserInput,
  type WorkspaceInput,
  type ProjectInput,
  type AssetInput,
  type GenerationJobInput,
  type ProviderConnectionInput,
  type ApiErrorInput,
  type DiagnosticsInput,
  type BillingSummaryInput,
  type DeviceRecordInput,
  type SessionRecordInput,
} from "./schemas.js";

export {
  ValidationError,
  validate,
  parseOrThrow,
  formatZodIssues,
  z,
  type ValidateResult,
  type ValidateSuccess,
  type ValidateFailure,
} from "./validate.js";

/** Re-export core domain types so consumers can pair schemas with @pvg/types. */
export type {
  ApiError,
  User,
  AuthUser,
  Workspace,
  Project,
  Asset,
  GenerationJob,
  ProviderConnection,
  Diagnostics,
  WorkspaceRole,
  Permission,
  BillingSummary,
  DeviceRecord,
  SessionRecord,
} from "@pvg/types";
